# Generated by Django 5.1.6 on 2025-02-12 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'indexes': [models.Index(fields=['email'], name='about_conta_email_4e80c9_idx'), models.Index(fields=['created_at'], name='about_conta_created_96f504_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImpactMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('icon_url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Impact Metric',
                'verbose_name_plural': 'Impact Metrics',
                'indexes': [models.Index(fields=['label'], name='about_impac_label_feca37_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('image_url', models.URLField(max_length=500)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'indexes': [models.Index(fields=['name'], name='about_teamm_name_24e829_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(db_index=True, max_length=100)),
                ('link', models.URLField(max_length=500)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='about.teammember')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'indexes': [models.Index(fields=['platform'], name='about_socia_platfor_5ce1ae_idx'), models.Index(fields=['team_member', 'platform'], name='about_socia_team_me_0bb0c7_idx')],
            },
        ),
    ]
