# Generated by Django 5.1.6 on 2025-02-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('avatar', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.URLField(max_length=500)),
                ('category', models.CharField(blank=True, choices=[('workshops', 'Workshops'), ('seminars', 'Seminars'), ('hackathons', 'Hackathons'), ('meetups', 'Meetups'), ('conferences', 'Conferences'), ('competitions', 'Competitions'), ('expos', 'Expos')], max_length=50)),
                ('is_registration_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.organizer')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['category'], name='events_even_categor_aca11d_idx'), models.Index(fields=['date'], name='events_even_date_5e8e1c_idx')],
            },
        ),
    ]
