# Generated by Django 5.1.6 on 2025-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrationLink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
