# Generated by Django 5.1.6 on 2025-02-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_registrationlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
    ]
